name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Compile
      run: npm run compile
      
    - name: Publish to VS Code Marketplace
      run: npx vsce publish -p ${{ secrets.VSCE_PAT }} 